export type TrainDataStoreType = {
  startDay: string;
  endDay: string;
  startTime: string;
  endTime: string;
  pay: string;
  trainType: string;
  trainNo: string;
  startStation: string;
  endStation: string;
  kid: number;
  adult: number;
  startStationForView: string;
  endStationForView: string;
  startDayForView: string;
  endDayForView: string;
  trainTypeForView: string;
  startTimeForView: string;
  selectStartTime: number;
  selectEndTime: number;
  selectTrainType: string;
  selectKid: number;
  selectAdult: number;
  selectPay: number;
  seatsId: string[];
  setStartDay: (type: string) => void;
  setEndDay: (type: string) => void;
  setStartTime: (type: string) => void;
  setEndTime: (type: string) => void;
  setPay: (type: string) => void;
  setTrainType: (type: string) => Promise<void>;
  setTrainNo: (type: string) => void;
  setStartStation: (type: string) => void;
  setEndStation: (type: string) => void;
  setKid: (type: number) => void;
  setAdult: (type: number) => void;
  setStartStationForView: (type: string) => void;
  setEndStationForView: (type: string) => void;
  setStartDayForView: (type: string) => void;
  setEndDayForView: (type: string) => void;
  setTrainTypeForView: (type: string) => void;
  setStartTimeForView: (type: string) => void;
  setSelectStartTime: (type: number) => void;
  setSelectEndTime: (type: number) => void;
  setSelectTrainType: (type: string) => void;
  setSelectKid: (type: number) => void;
  setSelectAdult: (type: number) => void;
  setSelectPay: (type: number) => void;
  setSeatsId: (type: string[]) => void;
};
